[tool.poetry]
name = "terminal_control"
version = "0.1.0"
description = "A tool for terminal control with Mac support"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"
pyautogui = "*"
keyboard = "*"
anthropic = "*"

[tool.pyright]
venvPath = "computer-use-demo"
venv = ".venv"
useLibraryCodeForTypes = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"